//The following code can be used to register a local version of the selected field group(s). A local field group can provide many benefits such as faster load times, version control & dynamic fields/settings. Simply copy and paste the following code to your theme's functions.php file or include it within an external file.
//

if( function_exists('acf_add_local_field_group') ):

acf_add_local_field_group(array(
	'key' => 'group_5d867f5bb068b',
	'title' => 'StructuralTop',
	'fields' => array(
		array(
			'key' => 'field_5d867f89222ec',
			'label' => 'Goal',
			'name' => 'goal',
			'type' => 'textarea',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'maxlength' => '',
			'rows' => 4,
			'new_lines' => '',
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'stc',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'side',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'field',
	'hide_on_screen' => '',
	'active' => true,
	'description' => '',
));

acf_add_local_field_group(array(
	'key' => 'group_5dd1eed3b46dd',
	'title' => 'SynthesisV1',
	'fields' => array(
		array(
			'key' => 'field_5dd1eed8a9ef1',
			'label' => 'Context',
			'name' => 'context',
			'type' => 'textarea',
			'instructions' => 'Where is this source? What is it where that is written? is that current reality?',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'new_lines' => '',
			'maxlength' => '',
			'placeholder' => '',
			'rows' => '',
		),
		array(
			'key' => 'field_5dd1eeeca9ef2',
			'label' => 'Issues',
			'name' => 'issues',
			'type' => 'textarea',
			'instructions' => 'Problematic, reality, issues',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'maxlength' => '',
			'rows' => 6,
			'new_lines' => '',
		),
		array(
			'key' => 'field_5dd1ef0aa9ef3',
			'label' => 'Concepts',
			'name' => 'concepts',
			'type' => 'textarea',
			'instructions' => 'Describe concepts (framework related to a references or raw concept)',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'maxlength' => '',
			'rows' => '',
			'new_lines' => '',
		),
		array(
			'key' => 'field_5dfffdcd5128c',
			'label' => 'Questions',
			'name' => 'questions',
			'type' => 'textarea',
			'instructions' => 'Questioning arising from that content',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'maxlength' => '',
			'rows' => 5,
			'new_lines' => '',
		),
		array(
			'key' => 'field_5dfff9720be2a',
			'label' => 'Hypothesis',
			'name' => 'hypothesis',
			'type' => 'textarea',
			'instructions' => 'Hypothesis are possible reality about this item that require experimentation for validation.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'maxlength' => '',
			'rows' => 4,
			'new_lines' => '',
		),
		array(
			'key' => 'field_5dd1ef1ba9ef4',
			'label' => 'Methodology',
			'name' => 'methodology',
			'type' => 'textarea',
			'instructions' => 'Methodology (Protocol, telescoped goal of the research, data collection and analysis)',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'maxlength' => '',
			'rows' => 4,
			'new_lines' => '',
		),
		array(
			'key' => 'field_5dd1ef3ba9ef5',
			'label' => 'Results',
			'name' => 'results',
			'type' => 'textarea',
			'instructions' => 'Results obtained by this source',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'maxlength' => '',
			'rows' => 5,
			'new_lines' => '',
		),
		array(
			'key' => 'field_5dd1ef4aa9ef6',
			'label' => 'Research Use',
			'name' => 'research_use',
			'type' => 'textarea',
			'instructions' => 'Usage in my research',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'maxlength' => '',
			'rows' => 5,
			'new_lines' => '',
		),
		array(
			'key' => 'field_5e09271057cb5',
			'label' => 'Limitations',
			'name' => 'limitations',
			'type' => 'textarea',
			'instructions' => 'Limits the content has or that you observed',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'maxlength' => '',
			'rows' => 6,
			'new_lines' => '',
		),
		array(
			'key' => 'field_5e03a5774defd',
			'label' => 'Contributions',
			'name' => 'contributions',
			'type' => 'textarea',
			'instructions' => 'What will it contribute to in terms of knowledge (which is more in the research protocol thought - But might be research use of this as reference contribution would do?',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'maxlength' => '',
			'rows' => 4,
			'new_lines' => '',
		),
		array(
			'key' => 'field_5e025b9097429',
			'label' => 'References',
			'name' => 'references',
			'type' => 'textarea',
			'instructions' => 'Related references / Bibliography',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'maxlength' => '',
			'rows' => 12,
			'new_lines' => '',
		),
		array(
			'key' => 'field_5e02fb0d2d300',
			'label' => 'Notes',
			'name' => 'notes',
			'type' => 'textarea',
			'instructions' => 'annotation',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'maxlength' => '',
			'rows' => '',
			'new_lines' => '',
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'post',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'side',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'field',
	'hide_on_screen' => array(
		0 => 'send-trackbacks',
	),
	'active' => true,
	'description' => 'The goal is that each post I create have a meta-system I can use to scientifically and creatively describe my observation, concepts, issues, methodologies, intentions...',
));

acf_add_local_field_group(array(
	'key' => 'group_5d867c15099eb',
	'title' => 'STCFields',
	'fields' => array(
		array(
			'key' => 'field_5d867c2209a9b',
			'label' => 'Due',
			'name' => 'duedate',
			'type' => 'date_time_picker',
			'instructions' => 'Set out Due date for the Goal',
			'required' => 1,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'display_format' => 'Y-m-d H:i:s',
			'return_format' => 'Y-m-d H:i:s',
			'first_day' => 1,
		),
		array(
			'key' => 'field_5d867dc9d9580',
			'label' => 'Current Reality',
			'name' => 'current_reality',
			'type' => 'textarea',
			'instructions' => 'Describe current reality in relationship to the goal',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'maxlength' => '',
			'rows' => '',
			'new_lines' => 'wpautop',
		),
		array(
			'key' => 'field_5d867e7fd9582',
			'label' => 'Acceptable result',
			'name' => 'mmot_acceptable_result',
			'type' => 'true_false',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'message' => '',
			'default_value' => 0,
			'ui' => 0,
			'ui_on_text' => '',
			'ui_off_text' => '',
		),
		array(
			'key' => 'field_5d867c5f09a9c',
			'label' => 'Note',
			'name' => 'note',
			'type' => 'text',
			'instructions' => 'Write a note on the goal',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
		array(
			'key' => 'field_5d867e3bd9581',
			'label' => 'Parent Chart',
			'name' => 'parent_chart',
			'type' => 'relationship',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '400',
				'class' => '',
				'id' => '',
			),
			'post_type' => array(
				0 => 'stc',
			),
			'taxonomy' => '',
			'filters' => array(
				0 => 'search',
				1 => 'post_type',
				2 => 'taxonomy',
			),
			'elements' => '',
			'min' => '',
			'max' => '',
			'return_format' => 'object',
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'stc',
			),
		),
	),
	'menu_order' => 2,
	'position' => 'acf_after_title',
	'style' => 'default',
	'label_placement' => 'left',
	'instruction_placement' => 'field',
	'hide_on_screen' => '',
	'active' => true,
	'description' => '',
));

endif;
